version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_HOST: "localhost"
      REACT_APP_BACKEND_URL: "http://localhost:5001"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      OPENAI_API_KEY: "your_token_here"
      OPENAI_API_BASE_URL: "https://api.vsegpt.ru/v1"
      OPENAI_MODEL_NAME: "google/gemini-2.5-flash-pre"
